global:
  scrape_interval:     20s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: proj
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - proj:8080